apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
# provisioner: ebs.csi.aws.com
provisioner: kubernetes.io/aws-ebs
# volumeBindingMode: WaitForFirstConsumer
volumeBindingMode: Immediate
parameters:
  type: gp2
